# Generated by Django 4.0 on 2021-12-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.BigIntegerField(blank=True, null=True)),
                ('product_id', models.BigIntegerField(blank=True, null=True)),
                ('sku_name', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=256, null=True)),
                ('salt_name', models.CharField(blank=True, max_length=256, null=True)),
                ('drug_format', models.CharField(blank=True, max_length=256, null=True)),
                ('pack_size', models.IntegerField(blank=True, null=True)),
                ('strength', models.CharField(blank=True, max_length=256, null=True)),
                ('product_banned_flag', models.BooleanField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=256, null=True)),
                ('price_per_unit', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
