# Generated by Django 4.0 on 2021-12-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='drug_format',
            new_name='drug_form',
        ),
    ]
